name: Build & Test
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Building and Testing
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1

            - name: Cache node modules
              # working-directory: ./ng-weather-app
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Node ${{ matrix.node-version }}
              # working-directory: ./ng-weather-app
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build:ci

            - name: Test
              working-directory: ./ng-weather-app
              run: npm run test:ci
